// Generated by tools/version.ps1. Do not edit by hand.
using System.Reflection;
[assembly: AssemblyVersion("0.2.0.0")]
[assembly: AssemblyFileVersion("0.2.167.0")]
[assembly: AssemblyInformationalVersion("0.2.167")]
[assembly: AssemblyTitle("Myoken Image Viewer")]
[assembly: AssemblyProduct("Myoken Image Viewer")]
[assembly: AssemblyDescription("Myoken Image Viewer - Windows photo browser and image viewer")]
namespace ZonerInspiredViewer
{
    internal static class BuildInfo
    {
        public const string Version = "0.2.167";
        public const string AppName = "Myoken Image Viewer";
        public const string WindowTitle = AppName + " v" + Version;
    }
}