param(
    [ValidateSet('Reserve', 'Complete')][string]$Action = 'Reserve',
    [string]$BuildNote = 'Rebuild of current source; see CHANGELOG.md.',
    [string]$Version,
    [ValidateSet('Built', 'Failed')][string]$Status = 'Built',
    [string]$OutputDirectory
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$statePath = Join-Path $root 'version.json'
$historyPath = Join-Path $root 'BUILD_HISTORY.json'
$utf8 = New-Object System.Text.UTF8Encoding($false)

function Write-GeneratedText([string]$Path, [string]$Content) {
    [System.IO.File]::WriteAllText($Path, $Content, $utf8)
}

$lock = [System.IO.File]::Open((Join-Path $root '.build-version.lock'), 'OpenOrCreate', 'ReadWrite', 'None')
try {
    $state = Get-Content -LiteralPath $statePath -Raw | ConvertFrom-Json
    $history = @(Get-Content -LiteralPath $historyPath -Raw | ConvertFrom-Json | ForEach-Object { $_ })
    if ($Action -eq 'Reserve') {
        foreach ($part in @($state.Major, $state.Minor, $state.Build)) {
            if ($null -eq $part -or $part -lt 0 -or $part -gt 65534 -or [int]$part -ne $part) { throw 'Invalid version.json component' }
        }
        $state.Build = [int]$state.Build + 1
        if ($state.Build -gt 65534) { $state.Build = 1; $state.Minor = [int]$state.Minor + 1 }
        $Version = '{0}.{1}.{2}' -f $state.Major, $state.Minor, $state.Build
        $stateJson = $state | ConvertTo-Json
        Write-GeneratedText $statePath $stateJson
        $history += [pscustomobject][ordered]@{
            Version = $Version
            StartedUtc = [DateTime]::UtcNow.ToString('o')
            CompletedUtc = $null
            Result = 'Started'
            Note = ($BuildNote -replace '[\r\n]+', ' ').Trim()
        }
        $assemblyVersion = '{0}.{1}.0.0' -f $state.Major, $state.Minor
        $generated = @"
// Generated by tools/version.ps1. Do not edit by hand.
using System.Reflection;
[assembly: AssemblyVersion("$assemblyVersion")]
[assembly: AssemblyFileVersion("$Version.0")]
[assembly: AssemblyInformationalVersion("$Version")]
[assembly: AssemblyTitle("Zen Image Viewer")]
[assembly: AssemblyProduct("Zen Image Viewer")]
[assembly: AssemblyDescription("Zen Image Viewer - Windows photo browser and image viewer")]
namespace ZonerInspiredViewer
{
    internal static class BuildInfo
    {
        public const string Version = "$Version";
        public const string AppName = "Zen Image Viewer";
        public const string WindowTitle = AppName + " v" + Version;
    }
}
"@
        Write-GeneratedText (Join-Path $root 'src\ZonerInspiredViewer\BuildInfo.cs') $generated
    }
    else {
        if ([string]::IsNullOrWhiteSpace($Version)) { $Version = '{0}.{1}.{2}' -f $state.Major, $state.Minor, $state.Build }
        $entry = $history | Where-Object { $_.Version -eq $Version } | Select-Object -Last 1
        if ($null -eq $entry) { throw "Version $Version has not been reserved" }
        $entry.Result = $Status
        $entry.CompletedUtc = [DateTime]::UtcNow.ToString('o')
        if ($PSBoundParameters.ContainsKey('BuildNote')) { $entry.Note = ($BuildNote -replace '[\r\n]+', ' ').Trim() }
    }
    Write-GeneratedText $historyPath (ConvertTo-Json -InputObject @($history) -Depth 6)
    $lines = @('# Build History', '', 'Generated by the build tools. Built means compilation succeeded; runtime tests are reported separately.', '')
    for ($i = $history.Count - 1; $i -ge 0; $i--) {
        $entry = $history[$i]
        $lines += @("## $($entry.Version)", '', "- Started (UTC): $($entry.StartedUtc)", "- Result: $($entry.Result)", "- Changes: $($entry.Note)", '')
    }
    Write-GeneratedText (Join-Path $root 'BUILD_HISTORY.md') ($lines -join "`r`n")
    if ($Action -eq 'Complete' -and $Status -eq 'Built' -and ![string]::IsNullOrWhiteSpace($OutputDirectory)) {
        [System.IO.Directory]::CreateDirectory($OutputDirectory) | Out-Null
        Write-GeneratedText (Join-Path $OutputDirectory 'VERSION.txt') ($Version + "`r`n")
        Copy-Item -LiteralPath (Join-Path $root 'CHANGELOG.md') -Destination $OutputDirectory -Force
        Copy-Item -LiteralPath (Join-Path $root 'BUILD_HISTORY.md') -Destination $OutputDirectory -Force
    }
    Write-Output $Version
}
finally { $lock.Dispose() }
